### ISSUE TITLE
Some tests fail when run in parallel on same machine

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/FileSystemGs#109]
The following tests failed when two filesystemtst/filesystemunittst.solo battery tests were run in parallel:
```smalltalk
FsDiskFileReferenceTest debug: #testCopyAllTo.
FsDiskFileReferenceTest debug: #testCopyTo.
FsDiskFileReferenceTest debug: #testUnicodeFilenames.
FsDiskFileReferenceTest debug: #testWorkingDirectoryParent.
FsDiskFileReferenceTest debug: #testWriteStreamDo.
```
Presumably they are using constant filenames and directory locations which can cause trouble for tests run concurrently ... a fairly common use case ...

**Comment by kurtkilpela** [comment]
Each test is now provided a unique sandbox folder. This resolves any contention in reused filenames when running in parallel since the tests are in independent folders.

See e156ffcc4c121405dd44ba9fefe4a65682dc3406
