### ISSUE TITLE
some supportedOrigins report root

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/FileSystemGs#115]
documentsPath and desktopPath are returning root, which is not an appropriate place to put anything.  

topaz 1> run
| report |
report := String new.
FileLocator supportedOrigins do: [:ea | report add: ea.  report add: (FileLocator perform: ea) absolutePath printString; lf].
report
%
...
documentsPath root
desktopPath root
...

**Comment by kurtkilpela** [comment]
This is due to two issues. 
1. #125 
2. `~/.config/user-dirs.dirs` is incorrectly configured for your account. It signifies that your documents directory (along with all other configured folders) should be your home directory.

I fixed #2. Once #1 is fixed, this will no longer be a problem.

**Comment by kurtkilpela** [comment]
Actually, since #2 is fixed, this should no longer appear problematic for you.

**Comment by kurtkilpela** [comment]
Problem 1 is also fixed.

**Comment by kurtkilpela** [comment]
Closing since this is resolved. If some further issue remains, feel free to re-open.
