### ISSUE TITLE
FS-specific Error class names and organization

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/FileSystemGs#118]
The FileException and FileSystemError hierarchies are inconsistently named and confusing, and contain some overlapping Errors.  While keeping names consistent with Pharo reduces the options, there are updates in progress to improve things. 

In addition, it's confusing to have a few of the classes prefixed with Fs while others are not.  I recommend renaming FsFileRequired, FsDirectoryRequired, and FsPersmissionDenied to remove the leading Fs. 
Removing Fs from FsFileDescriptorInvalid would be preferred.  This is more like the FileSystem errors.  

The FsUnixError classes can keep the Fs or not, they are kind of a separate set of classes.

**Comment by kurtkilpela** [comment]
Renaming occurred in 5c73b8d5a712897757f32b64ddfa4ff6e05cc230
