### ISSUE TITLE
Would like a nice way to do an append to a file

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/FileSystemGs#119]
There are a many readStream and writeStream variant methods, but what I really could use is AppendStream for writing output and log files.  This isn't there!

The workaround is to "pass an instance of FsUnixFileOpeningOptions to #writeStreamOptions:. You specify as part of the options that you wish to append. You can get the appropriate subclass of FsUnixFileOpeningOptions by sending #openingOptionsClass to a FileReference that you have.".

**Comment by LisaAlmarode** [comment]
While you might think you can use 
      FsFileOpeningOptions_Linux_x64 new append
This always gets invalidFileDescriptor errors. 

The workaround turns out to be easier than I expected, since writestreams on a file are also readable; all you need to do is be careful to do the setToEnd before writing.  The following works for my simple case:
```
  (FileSystem / '/gshost/test/abc.out') 
       writeStreamDo: [:str | str setToEnd. str nextPutAll: 'This is additional content'; lf].
```

while appendStreamDo: would be much safer, and more elegant, it's not terrible.

```
| fd |
fd := (FileSystem / '/gshost/test/abc.out') openWritable: true.
fd setToEnd.
fd write: 'This is additional content', (String with:Character lf) asByteArray.
fd close.
```

**Comment by kurtkilpela** [comment]
`#appendStreamDo:` is implemented in 188bb4f550d6bfd2c53b19def3c08f5b9b79ef55

**Comment by LisaAlmarode** [comment]
It has a half-baked look (relative to the rich set for read and write streams); we should add appendStream and ideally also appendStreamEncoded: and appendStreamEncodeded:do:

**Comment by kurtkilpela** [comment]
Additional selectors added in 6a75d7be64521e5c12f0d8d4f3c82f050a90abe9
