### ISSUE TITLE
Write/Read Stream Object Structure

### ISSUE THREAD

**Issue by regkrock** [GemTalk/FileSystemGs#13]
![image](https://user-images.githubusercontent.com/7550442/49775544-88952500-fcc6-11e8-8b8e-2cd52aeafc6f.png)

**Comment by regkrock** [comment]
Comment form Dale Henrichs:

Good questions.

Could you move this mail to a FileSystemGs issue? (yes in the FileSystemGs project) ... I want this discussion recorded on GitHub, so that it can be easily shared with others ... I've done some extra wrapping of streams with the buffered writeStreams because the encoding/decoding would (mostly) work for buffered write streams and I intend to remove the extra wrapping of Streams when we get FileSytems moved to Gs3.5.0/3.6.0 where we can get streaming encode/decode support ... some of the failing tests are markers for this and once we get to 3.5.0/3.6.0 the extra wrapping should be ripped out ...

Dale

**Comment by martinmcclure** [comment]
Dale -- I'm not sure what you mean by "extra" wrapping -- the stream stack that Reg sent looks reasonable.

Reg -- thanks for working on this and asking questions!

My initial thought is that it's OK to have BinaryFileStream be specific to GemStone, as it depends to some degree on the specifics of the underlying file primitives. FileReference/File (Pharo uses File, GS is currently using FileReference in this context) seems even more platform-specific, so removing or changing instvar names should be OK. 
I'd avoid the word "mode" though. It has two meanings. In "man 2 open", it means "file permissions". In "man 3 fopen" it means "some combination of open() flags that have nothing to do with file permissions".
Regards,
-Martin

**Comment by dalehenrich** [comment]
the "extra wrapping" comment comes from the fact that I was able to implement enough encoding/decoding for my purposes using the buffered streams in a stylized fashion ... proper encoding/decoding will require lower level support that may or may not be available in GemStone 5.0 ... I don't consider the current 3.2.15 to be complete with respect to encoding/decoding ...

I made the comment after looking at Reg's structure through the lens of my IPhone and don't know (even now) whether the use of buffered streams in these examples are the way that FileSystem was originally designed or because I had to shove buffered streams into the mix to get the encoding/decoding to work:) 

I seem to recall that my insertion of the buffered streams (used as encoder/decoder) was done in some of the tests and not inside of #writeStream where buffered streams would be naturally used ...

When I get a chance, I will spend time reviewing the actual content:)

**Comment by martinmcclure** [comment]
I ran Reg's example in Pharo 7. The stream stack there is the same as he reports. The biggest difference is that Pharo uses File where GS uses FileHandle.

**Comment by regkrock** [comment]
I moved the execution from File to FileHandle as a way to make the File/GsFile pluggable. I was following what I believe is the intent of the original developer(s) based on the ```flag:``` which is the figure 1 below. There are other places where the same flag: message.

I currently have only one reference to GsFile in the entire FileSystemGs code base. It is in the method ```FileSystem class>>#fileClass```. The messages being sent to GsFile need to be made compatible with the Pharo File messages. Once there are compatible messages, I believe we have a 'plug' compatible layer where any Smalltalk version can implement its file system access as it sees fit.

![image](https://user-images.githubusercontent.com/7550442/50046106-b7ffb500-006b-11e9-82cc-6b7001d11cc1.png)
Figure 1: In Pharo in FileHandle>>open, is the following code which shows the intent is to to move the work with the file from the AbstractBinaryFileStream and its subclasses to the FileHandle class:

**Comment by regkrock** [comment]
Action|Pharo | Gemstone
-------|------------ | -------------|
open - basic - where primitive is called|File class>>#open: name writable: writableFlag| GsFile>>#_openUsingGzip: aBoolean
 -|File name is utf8Encoded|aBoolean - if true, this is a compressed file.
_|writableFlag - indicates if read or write|
instance creation for opening|File class>>#open: name writable: writableFlag|GsFile class>>#open: aPathName mode: openMode  onClient: clientBool withCompression: compBool
open convenience methods||GsFile class>>#openCompressed: aPathName mode: openMode  onClient: clientBool 
_||GsFile class>>#openOnServerCompressed: aPathName mode: openMode
_||GsFile class>>#openReadCompressed: aPathName
_||GsFile class>>#openReadOnServerCompressed: aPathName
_||GsFile class>>#openWriteCompressed: aPathName
_||GsFile class>>#openWriteOnServerCompressed: aPathName
_||GsFile class>>#
_||GsFile class>>#
_||GsFile class>>#

**Comment by martinmcclure** [comment]
About pluggability and FileHandle, I'm thinking along these lines: 
* A high-level layer where code is in common between Pharo and GemStone.
* An interface layer, one class (or possibly more) whose code is different in Pharo and GemStone, but whose interface to the higher level is the same.
* Dialect-specific lower level that provides services to the interface layer.

In Pharo, it's hard to tell what the original intent of FileHandle was. It's quite old. But from some of the comments, and especially the class comment, it looks like it was intended to replace File. And if it did, I think this would improve matters significantly.

But I think that FileHandle is a good candidate for being the interface layer. For one thing, it's too good of a name to not use. We need an object represents an opened file, and FileHandle is a name that already means that in the non-Smalltalk world.

If we create a GemStone-specific version of FileHandle, and contribute back to Pharo code that allows it to have a consistent interface with the higher level classes like FileReference, perhaps we don't need to have a #fileClass method in FileSystem (which in Pharo does not reference File anyway).

I wouldn't try to make File and GsFile messages compatible, just have FileHandle send the correct messages for the current underlying layer.

**Comment by martinmcclure** [comment]
Re "Filename in Pharo is always converted to UTF-8." I believe that this is a bug in Pharo. This is always (or almost always) correct for Linux, but Windows wants UTF-16 filenames.
