### ISSUE TITLE
Remove unreferenced ZnCharacterReadWriteStream class

### ISSUE THREAD

**Issue by kurtkilpela** [GemTalk/FileSystemGs#134]
ZnCharacterReadWriteStream is not referenced in FileSystem or Rowan. Since it is not used or tested, it should be removed.

**Comment by dalehenrich** [comment]
Just a note that the other place that needs to be checked before deleting a class because of lack of references is a GLASS/Seaside image ... I've checked in one spot, but I've got at least one more place to look before I know that it is not referenced ...

**Comment by dalehenrich** [comment]
I searched all of GitHub and only found references to the class in the Pharo code base, where there are a large number of references ... but GLASS/Seaside will not be affected either ...

**Comment by kurtkilpela** [comment]
Removed in 80f42bf36b5a2c03fad75fa9519aba9d5c6e5ff3
