### ISSUE TITLE
POSIX Version Target

### ISSUE THREAD

**Issue by kurtkilpela** [GemTalk/FileSystemGs#50]
Linux supports extensions to POSIX not available on other platforms. For instance, O_PATH is an option that can be provided to `open`. This extension does not exist on macOS. The same is true in reverse. macOS supports O_SHLOCK which isn't present on Linux.

Initial versions of FileSystemGs targeted Linux and included various Linux extensions like O_PATH. In adding support for macOS, many of these differences were found and isolated into Linux specific classes.

macOS is [certified](https://www.opengroup.org/openbrand/register/brand3678.htm) against Unix 3 (POSIX.1-2001). Linux does not have a specific certification. It is up to each distro to provide as much (or little) POSIX compliance as it would like. (This is my understanding anyways.) In practice, we only use features in glibc which should be present on any system we will run on.

It seems like a better option, for the time being, to only support what is specified in POSIX (perhaps targeting POSIX.1-2001). Lower-level tests would target the behavior we use from this version of POSIX. Each test would test semantics rather than platforms-specific, low-level details such as the value of O_CREAT.

Separate low-level classes would persist to encode the details of O_CREAT and the function name to call.

Once we have a supported base, we could expand into platform-specific features as necessary.

See: #48

**Comment by kurtkilpela** [comment]
I am able to access [POSIX.1-2008](https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/) via The Open Group. I can access newer versions of the standard as well. I can't seem to find POSIX.1-2001.

**Comment by martinmcclure** [comment]
If you're going to go by POSIX, I'd recommend going with the latest, POSIX.1-2017. The changes that I know of between versions are mostly corrections of errors in the spec and changes to confirm more closely with actual practice.

**Comment by kurtkilpela** [comment]
That's good to know. I'll target [POSIX.1-2017](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/). I'll take the lowest common denominator between POSIX.1-2017, macOS, and Linux to serve as the base. Anything else can be added later as platform extensions.

**Comment by kurtkilpela** [comment]
Non-POSIX related features were removed in a serious commits ending with 85b701f82ebbccd97a2cda8958663156d0ba9238. Any additional non-POSIX cleanups will happen as they are found.
