### ISSUE TITLE
BinaryFileStream should not truncate on flush

### ISSUE THREAD

**Issue by kurtkilpela** [GemTalk/FileSystemGs#53]
In f219c5eede5f0fd0c385ed9125e34ab8156b3f8e, BinaryFileStream>>#flush was updated to truncate the file to the current position. This was implemented as Rowan did not seem to truncate existing files when writing packages out to disk.

This should be reverted. If there is still an issue where package files aren't truncated, Rowan should be updated to properly truncate.

**Comment by dalehenrich** [comment]
out of curiosity ... what would be the proper way to truncate files?

**Comment by kurtkilpela** [comment]
Sending #truncate to the stream would be sufficient.

**Comment by dalehenrich** [comment]
So I would be expected to call truncate / close for every file on the off
chance that it existed before and that it was larger before hand?

**Comment by dalehenrich** [comment]
... should #close do a truncate ... instead of flush?

**Comment by kurtkilpela** [comment]
I imagine the pattern would be `stream flush; truncate; close`. The problem with having truncate occur automatically, is that you may not actually want it. It is hard to work around if it happens automatically.

You could open a file stream, seek to a record in the middle of a file, write a few bytes to change the record, and then close it. If we automatically truncate the file, you'd always have to read the full file in, make the changes, and then write the whole file out. That doesn't scale well.

(Alternatively, in the Rowan case, you could truncate after opening the file.)

**Comment by martinmcclure** [comment]
In Pharo, sending truncate to a file stream appears to truncate the file to position 0; i.e. wipes the entire contents. So you wouldn't want to do that after writing contents you wanted to keep.

If you want to write an entire file, possibly creating it but not keeping any previous contents, the best way to do that is to specify the truncate option when opening the file. This results in the open() system call having the O_TRUNC flag set, and may not yet be supported by FileSystemGs (but should be at some point). 
Alternatively, truncating after opening, as Kurt suggests, should work.

**Comment by kurtkilpela** [comment]
Yeah, I saw that behavior in Pharo. It wasn't yet clear to me that that was correct behavior. I suppose we will take the semantics since we are porting FileSystem. They do have a second selector #truncate: which allows you to truncate to any position.

The simplest thing would be to just truncate immediately after opening the file.

**Comment by dalehenrich** [comment]
ah, so an #openTruncate, in the same vein as #openAppend would be desired
then? ... keep in mind that I don't know what the #openAppend pattern looks
like either :)

**Comment by kurtkilpela** [comment]
Pharo FileReference doesn't have an #openAppend. Pharo's File class does have an #openForAppend.

It would be possible for us to add several open methods. Or we could have an open that takes a FileOpeningOptions instance (which is the direction we've been heading.)

**Comment by martinmcclure** [comment]
The unary selector #truncate truncating to any position but zero would be quite unexpected behavior, so I think that Pharo's behavior is the expected one.

For opening options I think there should be #openFoo for only the most common options, for everything else use a FileOpeningOptions. Maybe something like ``myFileReference openWithOptions: FileOpeningOptions write truncate.``

**Comment by kurtkilpela** [comment]
I find it a little weird that #truncate doesn't truncate to the current position for a Stream. I would agree that a send of #truncate to an instance of UnixFileDescriptor doing anything other than truncate to zero would be weird.

**Comment by dalehenrich** [comment]
Either openX or openWithOptions: would work for me ... seems that openX
variants that call openWithOptions: for the common combos, would be useful
...

**Comment by dalehenrich** [comment]
Hmmm, if I am fiddling with the internal bits of an existing file, I would
agree that truncate to current position would be one of things that might
be useful to be able to do ... although I have to admit, I tend to rewrite
an entire file when I want to change internal bits (truncate to 0) and
don't have personal experience with fiddling with internals of a file, but
it seems to be dicey business to be inserting and deleting bytes while
keeping in mind the original end of file on disk so that you can make sure
they are not left hanging around ... (truncate on flush would be a useful
operation in this case, I suppose)

**Comment by martinmcclure** [comment]
It seems odd to me to have streams respond to ``truncate`` at all, it has no obvious meaning to me. Maybe ``truncateToHere`` as a shortcut for ``stream truncateTo: stream position``, but there's the Pharo precedent to worry about.

**Comment by dalehenrich** [comment]
I suppose defaulting to Pharo behavior is not a bad way to go for `truncate`, while `openWithOptions:` (with short cuts) meets our needs and is an intentional departure from Pharo anyway ...

**Comment by kurtkilpela** [comment]
Matching the Pharo behavior is the best answer. Pharo does have a #truncate: which allows you to truncate to a specific length.

**Comment by kurtkilpela** [comment]
Added AbstractFileReference>>#truncatedWriteStreamDo:. Rowan's pattern is to use #writeStreamDo:. This new selector will truncate the file before evaluating the argument and should be a sufficient replacement for Rowan. See 0cac5ba6e4264cd7a2ddbe6ee07e14a437ae84b1.

Once Rowan has swapped to #truncatedWriteStreamDo:, #flush can stop truncating the file to the current position.

**Comment by kurtkilpela** [comment]
Note to self: sending `#truncate` to a stream, results in truncating the file to position 0, not the current position.

**Comment by kurtkilpela** [comment]
Per conversation with Dale, remove `#truncatedWriteStreamDo:` and `#appendingWriteStreamDo:`. Instead, the stream will just be created in appending mode. In the case of truncation, the file will be truncated as the first action in the `#writeStreamDo:` block argument.

**Comment by kurtkilpela** [comment]
844685fd44263955d026e8a9546467bb277e46fb removes the previous send of #truncate in #flush. See #105

**Comment by kurtkilpela** [comment]
c0282f0b5a593a4848898762f1d4885479e786c9 removes `#truncatedWriteStreamDo:` and '#appendingWriteStreamDo:`.

Rowan will send #truncate to the stream as necessary.

**Comment by kurtkilpela** [comment]
6fe072f44a294e611f36e95786bc18b0862b8486 ensures files are truncated to a length of zero bytes when an associated write stream receives `#truncate`.
