### ISSUE TITLE
ZnCharacterStreamTests  #testUpToAll and #testUpToAllTwice are now failing

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/FileSystemGs#79]
These two tests were skipped dating back to my original port of FileSystem to GemStone and today I turned the testing back on and the tests are now failing ... so it is time for me to pay the piper and bring the #upToAll: implementation up to snuff

**Comment by dalehenrich** [comment]
as of this commit [69e837d], I believe that the #upToAll: implementation is complete, however, there seem to be some issues with the #position method and ZnCharacterReadStream on UTF8 encoded streams:
```smalltalk
	| string bytes stream res |
	string := 'eißendeße'.
	bytes := ZnUTF8Encoder new encodeString: string.
	stream := (ZnCharacterReadStream on: bytes readStreamPortable).
	res := stream next; next; next.
	self assert: res equals: $ß.
	self assert: stream position equals: 3.
```
So will hold off until the issue is resolved..

**Comment by dalehenrich** [comment]
Issue #80 reports the [above problem](https://github.com/GemTalk/FileSystemGs/issues/79#issuecomment-1345428626)

**Comment by dalehenrich** [comment]
Will close this issue in anticipation of Issue #80 resolving the [current test failures](https://github.com/GemTalk/FileSystemGs/issues/75#issuecomment-1351809660), but can be re-opened if necessary

**Comment by kurtkilpela** [comment]
I switched implementations of #upToAll: and updated #testUpToAllTwice which was using `(Character codePoint: 150)` and similar expressions. These are out of range of Unicode7. They cause it to promote to Unicode16, which the 8BitEncoder is not designed to support. I disabled them when the `#stringClass` is Unicode7.

See 391b3e41161fd046c9b6e504ea6409a59d61808e.
