### ISSUE TITLE
FileLocator>>serverWorkingDirectory gets MNU 

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/FileSystemGs#87]
```
a MessageNotUnderstood occurred (error 2010), a FileSystem class does not understand  #'server'
```

Stack attached

`clientWorkingDirectory` seems to have a similar problem. 

[20221219_rowanServerStackDump.txt](https://github.com/GemTalk/FileSystemGs/files/10262712/20221219_rowanServerStackDump.txt)

**Comment by kurtkilpela** [comment]
This is already fixed in the newer version of FIleSystem. Since FileSystem is server-only, we have `FileLocator class>>#workingDirectory` available.
