### ISSUE TITLE
AbstractFileReference>>fileNames uses Pharo-specific pattern

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/FileSystemGs#93]
The following code is specific to Pharo:
```
fileNames
	^ self files collect: #basename
```
So we're missing tests for this puppy, as well ... there may be other places where this pattern has snuck in ... 

Noticed that #filesMatching: went missing (was [present in old FileSystem](https://github.com/GemTalk/Rowan/blob/masterV2.4/platforms/gemstone/projects/FileSystemGs/rowan/src/FileSystem-Core/AbstractFileReference.class.st#L437-L447)) and #fileNames was my first stop for fashioning a replacement :smile: ...

**Comment by kurtkilpela** [comment]
Fixed this along w/ AbstractFileReference>>#directoryNames in e56296a113bd39bc642547407dfadcbba3eada59
