### ISSUE TITLE
String>>asPath ... no CharacterCollextion>>asPath?

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/FileSystemGs#96]
The implication of this is that I think this would excludes multi-byte Unicode filenames ...

**Comment by dalehenrich** [comment]
Most of the other FileSystem extension methods are already in CharacterCollection, so I assume this IS an oversight

**Comment by kurtkilpela** [comment]
This is an oversight but it does reveal a problem. In method AbsolutePath>>@removeRedundantSegments:, each segment is compared against the literal `'.'`. This causes an ArgumentError stating 'non-Unicode argument disallowed in Unicode comparison'. There are likely other places similar to this.

One possible solution would be to use `#compareTo:collator:` to avoid this problem. This would mean we would be comparing UnicodeX instances and String instances, ignoring the Unicode compare flag.

Alternatively, I can test Unicode only when that flag is set. When that flag isn't set, FileSystem would be restricted to non-UnicodeX String classes.

I am thinking that honoring the flag is likely better than ignore it. Thoughts, Dale?

**Comment by kurtkilpela** [comment]
a7b93bdc173eb2a4a419c4902e3eff7d705ec91d moves #asPath to CharacterCollection. The test assumes GemStone is running in Unicode Comparison Mode. This will need to change as it will fail in Legacy Comparison Mode.

**Comment by dalehenrich** [comment]
> Alternatively, I can test Unicode only when that flag is set. When that flag isn't set, FileSystem would be restricted to non-UnicodeX String classes.
I think that is fair ... mixing Unicode and String classes without enabling Unicode comparison mode is fraught with errors ... everywhere

**Comment by kurtkilpela** [comment]
That's my thinking too. I'll switch the test to run the Unicode part only in Unicode comparison mode.

**Comment by kurtkilpela** [comment]
8b0abbb8046dcdcd44a30cfc6b69975881a83e80 ensures test can pass in both string comparison modes.
